twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        app_name: "%env(APP_NAME)%"
        articleCategoryService: '@App\Repository\ArticleCategoryRepository'

when@test:
    twig:
        strict_variables: true
